### ISSUE TITLE
question about  User defined PTM

### ISSUE THREAD

**Issue by hemingwang** [biodavidjm/artMS#178] opened 2021-04-16 02:46 UTC
Hi,
When I run the artMS,  I want to use my modification. But I found it has mistake.
my artMS version is 1.8.3
my config file is:
data:
    modifications: PTM:STY:ph
my R code is:
artmsQuantification(yaml_config_file = "my_config.yaml")

the R console is:
> artmsQuantification(yaml_config_file = "my_config.yaml")
The PTM name used in the evidence file, and the third position in PTM:STY:PH must be all lowercase characters
Error in artmsQualityControlEvidenceBasic(evidence_file = config$files$evidence,  : 
  Error: unexpected format for specifying a user-defined modification typePTM:STY:PH

I am looking forward to your reply.

**Comment by biodavidjm** [comment] 2021-04-16 05:22
Hi @hemingwang ,

this should be an easy fix. As the error is indicating, you just need to replace `PTM:STY:PH` by `PTM:STY:ph` ("`ph`" must be lower case, same as MaxQuant. 

However, as explained in the vignette, that's the "general" form. For phosphorylation is one of the 3 main PTMs most frequently PTMs so they have their own "shortcut". So you can directly use `PH`, i.e., in the configuration file:

`modifications: PH`

Please, give it a try and let us know how it goes.

Thanks!

**Comment by hemingwang** [comment] 2021-04-16 05:57
Thank you help me in patience!
At the beginning, I want to use my defined PTM(ad). So I write  PTM:STY:ad in the config file. The console result is "I used the AD". So I feel puzzled. 
Then I write  PTM:STY:ph in the config file. It is the same wrong.
But I write  PH in the config file is no wrong.

Best wishes!

**Comment by biodavidjm** [comment] 2021-04-16 06:09
Not sure I fully understand what the problem was. Not sure what PTM:STY:ad is. Would you mind clarifying? And PTM:STY:ph should have worked (I cannot reproduce the error, on our side, PTM:STY:ph works perfectly. 

How did you install artMS? what type of posttranslational modification did you search in MaxQuant? phosphorylation? (I don't know what "AD" is). It would help us a lot if you could provide the exact error that you get when you run a configuration file with "PTM:STY:ph". Would you mind sharing?

Thanks!

**Comment by biodavidjm** [comment] 2021-04-29 16:17
Closing the issue. Please, don't hesitate to re-open it if you have anything else to add

**Closed by biodavidjm** 2021-04-29 16:17 UTC
